load('Data_solution/pfw.mat')
load('Data_solution/pvw.mat')
load('Data_solution/solR.mat')
load('Data_solution/solSig.mat')
load('Data_solution/solSiw.mat')
load('Data_solution/solT.mat')
load('Data_solution/solT_end.mat')
load('Data_solution/solTemp.mat')
load('Data_solution/solU.mat')
load('Data_solution/TEvec.mat')

plot_thaw1(solT,solTemp,solR,solU,solSig,solSiw,pfw,pvw)
plot_thaw2(solT,solT_end,solTemp,solR,solU,solSig,solSiw,pfw,pvw)
plot_thaw3(solT,solTemp,solR,solU,solSig,solSiw,pfw,pvw)
